name: Build Windows Executable

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  LANG: zh_CN.UTF-8
  LC_ALL: zh_CN.UTF-8
  PYTHONUTF8: 1

permissions:
  contents: write  # 必须的仓库权限

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Release Tag
      shell: powershell
      run: |
        $DATE = (Get-Date).ToString("yyyy-MM-dd")
        $VERSION = "v1"  # 版本号，每次发布时递增
        $RELEASE_TAG = "$DATE-$VERSION"
        "RELEASE_TAG=$RELEASE_TAG" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pyinstaller

    - name: Build executable
      shell: cmd
      run: |
        python -m PyInstaller --noconfirm --onefile --console ^
          --add-data "src/data;src/data" ^
          --add-data ".env.example;." ^
          --add-data "turnstilePatch;turnstilePatch" ^
          --name "CursorAutoFree" ^
          "run.py"

        copy README_win.md dist\
        copy .env.example dist\.env.example
                
        cd dist
        powershell "Compress-Archive -Path * -DestinationPath CursorAutoFree_Windows.zip"

    - name: Upload Release
      shell: powershell
      run: |
        gh release create "$env:RELEASE_TAG" `
          dist/CursorAutoFree_Windows.zip `
          --title "Release $env:RELEASE_TAG" `
          --notes "Windows Auto Build Version $($env:RELEASE_TAG)"
          
      env:
        GH_TOKEN: ${{ github.token }}  # 使用GitHub自动生成的token