name: Build Windows Executable

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  LANG: zh_CN.UTF-8
  LC_ALL: zh_CN.UTF-8
  PYTHONUTF8: 1  # 强制Python使用UTF-8编码

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Release Tag
      shell: powershell
      run: |
        # 强制使用带BOM的UTF-8编码
        $PSDefaultParameterValues['*:Encoding'] = 'utf8bom'
        $RELEASE_TAG = (Get-Date).ToString("yyyy-MM-dd")
        "RELEASE_TAG=$RELEASE_TAG" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8bom -Append

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pyinstaller -i https://pypi.tuna.tsinghua.edu.cn/simple
      
    - name: Check directory structure
      shell: cmd
      run: |
        dir
        dir src
        dir turnstilePatch
    
    - name: Build executable
      shell: cmd
      run: |
        python -m PyInstaller --noconfirm --onefile --console ^
          --add-data "src/data;src/data" ^
          --add-data ".env.example;." ^
          --add-data "turnstilePatch;turnstilePatch" ^
          --name "CursorAutoFree" ^
          --hidden-import=dotenv ^
          --hidden-import=requests ^
          --hidden-import=colorama ^
          --hidden-import=DrissionPage ^
          --hidden-import=selenium ^
          --hidden-import=webdriver_manager ^
          "run.py"

        copy requirements.txt dist\
        copy README.md dist\
        copy .env.example dist\.env.example
        
        echo @echo off > dist\启动程序.bat
        echo title Cursor Half Auto >> dist\启动程序.bat
        echo echo 正在启动Cursor Half Auto... >> dist\启动程序.bat
        echo CursorAutoFree.exe >> dist\启动程序.bat
        echo pause >> dist\启动程序.bat
        
        cd dist
        powershell "Compress-Archive -Path *.exe, *.bat, *.env.example, *.md, *.txt -DestinationPath CursorAutoFree_Windows.zip"
    
    - name: Create artifact directory
      shell: powershell
      run: |
        # 强制创建目录并设置编码
        $PSDefaultParameterValues['*:Encoding'] = 'utf8bom'
        New-Item -ItemType Directory -Force -Path artifact

    - name: Copy artifact
      shell: cmd
      run: copy dist\CursorAutoFree_Windows.zip artifact\
    
    - name: Release Artifact
      shell: powershell
      run: |
        # 设置完整的编码环境
        $PSDefaultParameterValues['*:Encoding'] = 'utf8bom'
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        [System.Environment]::SetEnvironmentVariable('LC_ALL', 'zh_CN.UTF-8')
        
        # 使用here-string定义中文内容
        $notes = @"
        Windows 可执行文件自动构建
        版本日期: $env:RELEASE_TAG
        包含以下文件:
        - 主程序: CursorAutoFree.exe
        - 启动脚本: 启动程序.bat
        - 环境配置示例: .env.example
        "@
        
        # 执行发布命令
        gh release create "$env:RELEASE_TAG" `
          artifact/CursorAutoFree_Windows.zip `
          --title "Release $env:RELEASE_TAG" `
          --notes "$notes" `
          --repo $env:GITHUB_REPOSITORY
        
        # 验证发布结果
        Write-Output "=== 发布验证 ==="
        gh release view "$env:RELEASE_TAG" --json assets
      env:
        GH_TOKEN: ${{ secrets.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 }}
        GITHUB_REPOSITORY: ${{ github.repository }}
