name: Build Windows Executable

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pyinstaller -i https://pypi.tuna.tsinghua.edu.cn/simple
    
    - name: Build executable
      run: |
        # 构建Windows可执行文件
        python -m PyInstaller --noconfirm --onefile --console ^
          --add-data "src/data;src/data" ^
          --add-data ".env.example;." ^
          --add-data "turnstilePatch;turnstilePatch" ^
          --add-data "src/main.py;src" ^
          --name "CursorAutoFree" ^
          --hidden-import=dotenv ^
          --hidden-import=requests ^
          --hidden-import=colorama ^
          --hidden-import=DrissionPage ^
          --hidden-import=selenium ^
          --hidden-import=webdriver_manager ^
          "run.py"
        
        # 复制必要文件到发布目录
        copy requirements.txt dist\
        copy README.md dist\
        copy .env.example dist\.env.example
        
        # 创建启动批处理文件
        echo @echo off > dist\启动程序.bat
        echo title Cursor Half Auto >> dist\启动程序.bat
        echo echo 正在启动Cursor Half Auto... >> dist\启动程序.bat
        echo CursorAutoFree.exe >> dist\启动程序.bat
        echo pause >> dist\启动程序.bat
        
        # 压缩文件
        cd dist
        Compress-Archive -Path CursorAutoFree.exe, 启动程序.bat, .env.example, README.md, requirements.txt -DestinationPath CursorAutoFree_Windows.zip
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CursorAutoFree_Windows
        path: dist/CursorAutoFree_Windows.zip
    
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/CursorAutoFree_Windows.zip
        asset_name: CursorAutoFree_Windows.zip
        asset_content_type: application/zip 